spring:
  application:
    name: xiaolizi-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.xiaolizi.ai: DEBUG